import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { slugify } from "../docs";
import { listChangelogs } from "../changelog";
import { CONTEXT_CHARS } from "./config";

// search over the site's markdown (knowledge/, generated by `pnpm knowledge`).
// this is classic retrieval (bm25) done on the server, with no model calls and
// no embeddings: for each question, 2-3 chunks are picked and only those travel
// in the prompt. the corpus is small (about 100 chunks), so this is plenty.

interface Chunk {
	title: string; // page
	heading: string; // section within the page ("" = intro)
	url: string; // with an anchor when the section has one
	text: string;
	terms: Map<string, number>;
	length: number;
	lead?: boolean; // opening of a general page: scores a bit higher
}

interface Page {
	title: string;
	url: string;
	kind: string;
	body: string;
}

interface Index {
	chunks: Chunk[];
	sitemap: string;
	stamp: number;
}

export interface Hit {
	title: string;
	heading: string;
	url: string;
	text: string;
	score: number;
}

const MAX_PART_CHARS = 800;
const K1 = 1.4;
const B = 0.75;
const LEAD_BOOST = 1.25;
const MIN_SCORE = 2.5; // below this, nothing is relevant: better not to inject noise
const CHANGELOG_TTL_MS = 5 * 60_000;
const INDEX_CHECK_INTERVAL_MS = 5000;

// spanish stopwords + the ones that show up most in questions asked to a bot.
const STOP = new Set(
	`a al algo ante aqui asi aun aunque cada como con cual cuando de del desde donde dos el ella ellos en entre era es esa ese eso esta este esto estoy fue ha hace hacer han hasta hay la las le les lo los mas me mi mis mucho muy no nos nosotros o os otra otro para pero poco por porque puedo puede pueden que quien quiero se si sin sobre son su sus tambien te tengo ti tiene tu tus un una uno unos y ya yo hola gracias por favor quiero necesito podria saber`.split(
		/\s+/,
	),
);

/**
 * the assistant's search index over the site's docs and changelog: a small
 * in-memory bm25 engine, rebuilt from the markdown files whenever they change.
 */
export class KnowledgeBase {
	private index: Index | null = null;
	private lastCheck = 0;
	private changelogChunks: Chunk[] = [];
	private changelogLoadedAt = 0;

	private knowledgeDir(): string {
		return resolve(process.env.KNOWLEDGE_DIR || "knowledge");
	}

	/**
	 * normalizes and trims each word to an approximate stem, so "banear",
	 * "baneado" and "baneo" (or "bots" and "bot") match. not a full stemmer,
	 * and doesn't need to be: it only has to group closely enough for a corpus this small.
	 */
	private tokenize(text: string): string[] {
		const words = text
			.normalize("NFD")
			.replace(/[̀-ͯ]/g, "")
			.toLowerCase()
			.match(/[a-z0-9]+/g);

		return (words ?? [])
			.filter((w) => w.length > 1 && !STOP.has(w))
			.map((w) => {
				let s = w;
				if (s.length > 3) s = s.replace(/(aciones|iciones|ciones|cion|amiento|ando|iendo|ados|idos|ado|ido|ar|er|ir|es|s)$/, "");
				if (s.length > 4) s = s.replace(/[aeo]$/, "");
				return s;
			});
	}

	private countTerms(tokens: string[], boost: string[] = []): Map<string, number> {
		const terms = new Map<string, number>();
		for (const t of tokens) terms.set(t, (terms.get(t) ?? 0) + 1);
		// what appears in the title or the heading weighs more (x3).
		for (const t of boost) terms.set(t, (terms.get(t) ?? 0) + 3);
		return terms;
	}

	private makeChunk(input: { title: string; heading: string; url: string; text: string }): Chunk {
		const terms = this.countTerms(this.tokenize(input.text), this.tokenize(`${input.title} ${input.heading}`));
		return { ...input, terms, length: [...terms.values()].reduce((a, b) => a + b, 0) };
	}

	/**
	 * splits a long text into small parts, cutting along lines. small parts
	 * score more precisely (a 14-row table would dilute every row) and cost
	 * less once injected. if the text starts with a table, every part repeats
	 * its header so the rows still make sense.
	 */
	private splitLong(text: string): string[] {
		if (text.length <= MAX_PART_CHARS) return [text];

		const lines = text.split("\n");
		const tableHeader = lines[0]?.startsWith("|") && /^\|[\s|:-]+\|$/.test(lines[1] ?? "") ? `${lines[0]}\n${lines[1]}` : "";
		const parts: string[] = [];
		let current = "";
		for (const line of lines) {
			if (current && current.length + line.length > MAX_PART_CHARS) {
				parts.push(current);
				current = tableHeader && line.startsWith("|") ? tableHeader : "";
			}
			current += `${current ? "\n" : ""}${line}`;
		}
		if (current) parts.push(current);
		return parts;
	}

	private parsePage(source: string): Page | null {
		const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
		if (!match) return null;
		const meta = Object.fromEntries(
			match[1].split("\n").map((line) => {
				const i = line.indexOf(":");
				return [line.slice(0, i).trim(), line.slice(i + 1).trim()];
			}),
		);
		if (!meta.title || !meta.url) return null;
		// without the leading "# title" (already in the metadata).
		return { title: meta.title, url: meta.url, kind: meta.kind ?? "", body: match[2].replace(/^\s*# .*\n/, "") };
	}

	private chunkPage(page: Page): Chunk[] {
		const chunks: Chunk[] = [];
		const [intro, ...sections] = page.body.split(/\n## /);

		// on general pages (terms, privacy, testimonials…) the title weighs the
		// same in every chunk, and "what are the terms?" would get answered by
		// any random section. the first two (the intro and the first section)
		// get a small edge: that's where the page says what it is.
		let added = 0;
		const add = (heading: string, text: string) => {
			const url = heading && page.kind === "docs" ? `${page.url}#${slugify(heading)}` : page.url;
			const lead = page.kind === "site" && added++ < 2;
			for (const part of this.splitLong(text.trim())) if (part) chunks.push({ ...this.makeChunk({ title: page.title, heading, url, text: part }), lead });
		};

		add("", intro);
		for (const section of sections) {
			const newline = section.indexOf("\n");
			add(section.slice(0, newline === -1 ? undefined : newline).trim(), section);
		}
		return chunks;
	}

	private sourceStamp(dir: string): number {
		return readdirSync(dir).reduce((max, file) => Math.max(max, statSync(join(dir, file)).mtimeMs), 0);
	}

	/** the changelog lives in sqlite and changes without a deploy: reread every 5 minutes. */
	private loadChangelog(): Chunk[] {
		if (Date.now() - this.changelogLoadedAt < CHANGELOG_TTL_MS) return this.changelogChunks;
		this.changelogLoadedAt = Date.now();
		try {
			this.changelogChunks = listChangelogs()
				.slice(0, 8)
				.flatMap((entry) => {
					const heading = [entry.name, entry.version].filter(Boolean).join(" ") || entry.title;
					return this.splitLong(entry.markdown.trim()).map((part) => this.makeChunk({ title: "Changelog", heading, url: `/changelog/${entry.slug}`, text: part }));
				});
		} catch {
			this.changelogChunks = [];
		}
		return this.changelogChunks;
	}

	private build(dir: string, stamp: number): Index {
		const chunks: Chunk[] = [];
		for (const file of readdirSync(dir)) {
			if (!file.endsWith(".md") || file.startsWith("_")) continue;
			const page = this.parsePage(readFileSync(join(dir, file), "utf8"));
			if (page) chunks.push(...this.chunkPage(page));
		}

		const sitemapFile = join(dir, "_sitemap.md");
		return {
			chunks,
			sitemap: existsSync(sitemapFile) ? readFileSync(sitemapFile, "utf8").trim() : "",
			stamp,
		};
	}

	private ensureIndex(): Index | null {
		const dir = this.knowledgeDir();
		if (!existsSync(dir)) return null;

		// checks for changes at most every 5s (in development, so it doesn't
		// restart while regenerating; in production nothing changes anyway).
		if (!this.index || Date.now() - this.lastCheck > INDEX_CHECK_INTERVAL_MS) {
			this.lastCheck = Date.now();
			const stamp = this.sourceStamp(dir);
			if (!this.index || this.index.stamp !== stamp) this.index = this.build(dir, stamp);
		}
		return this.index;
	}

	knowledgeReady(): boolean {
		return this.ensureIndex() !== null;
	}

	/** list of pages (title and path) for the system prompt. */
	siteMap(): string {
		return this.ensureIndex()?.sitemap ?? "";
	}

	search(query: string, limit: number): Hit[] {
		const base = this.ensureIndex();
		if (!base) return [];

		const chunks = [...base.chunks, ...this.loadChangelog()];
		const queryTerms = [...new Set(this.tokenize(query))];
		if (!queryTerms.length || !chunks.length) return [];

		const docFreq = new Map<string, number>();
		let totalLength = 0;
		for (const chunk of chunks) {
			totalLength += chunk.length;
			for (const term of chunk.terms.keys()) docFreq.set(term, (docFreq.get(term) ?? 0) + 1);
		}
		const avgLength = totalLength / chunks.length;

		const scored = chunks.map((chunk) => {
			let score = 0;
			for (const term of queryTerms) {
				const tf = chunk.terms.get(term);
				if (!tf) continue;
				const n = docFreq.get(term) ?? 0;
				const idf = Math.log(1 + (chunks.length - n + 0.5) / (n + 0.5));
				score += (idf * tf * (K1 + 1)) / (tf + K1 * (1 - B + (B * chunk.length) / avgLength));
			}
			return { chunk, score: chunk.lead ? score * LEAD_BOOST : score };
		});

		const ranked = scored.filter((s) => s.score >= MIN_SCORE).sort((a, b) => b.score - a.score);
		const top = ranked[0]?.score ?? 0;

		return ranked
			.filter((s) => s.score >= top * 0.45)
			.slice(0, limit)
			.map(({ chunk, score }) => ({
				title: chunk.title,
				heading: chunk.heading,
				url: chunk.url,
				text: chunk.text.length > CONTEXT_CHARS ? `${chunk.text.slice(0, CONTEXT_CHARS)}…` : chunk.text,
				score,
			}));
	}

	/**
	 * real site routes with their title, so the chat only turns into a button
	 * the ones that exist (a route the model makes up stays as plain text).
	 */
	siteRoutes(): Record<string, string> {
		const routes: Record<string, string> = { "/docs": "Documentación", "/support/assistant": "Asistente de IA", "/dashboard": "Dashboard" };
		for (const line of this.siteMap().split("\n")) {
			const match = /^- (.*) \((\/[^)]*)\)$/.exec(line);
			if (match && !routes[match[2]]) routes[match[2]] = match[1];
		}
		return routes;
	}
}

export const knowledgeBase = new KnowledgeBase();
